version: '3'
services: 
    frontend:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        command: npm run start
        container_name: renta_frontend
        ports:
            - "3000:3000"        
        volumes: 
            - ./:/renta_frontend
            - /renta_frontend/node_modules
